### ISSUE TITLE
Long time to fetch

### ISSUE THREAD

**Issue by jpike88** [mikhail-angelov/gulp-translations-from-spreadsheet#5]
Takes like 40 seconds for 50 rows

**Comment by mikhail-angelov** [comment]
I see problem, sometime it try to load too many empty columns 
I'll add one more option to specify column count, it should help

**Comment by mikhail-angelov** [comment]
gulp-translations-from-spreadsheet@1.2.0 
colCount options added

**Comment by jpike88** [comment]
I can improve this and have it detect the outer most columns by default. I’ll make a pull request shortly

**Comment by mikhail-angelov** [comment]
This will be great!
